colors:
  body: none
  date: none
  tags: none
  title: none
default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
indent_character: '|'
journals:
  pers:
    encrypt: false
    journal: ~/Dropbox/jrnls/personal.txt
  prof: ~/Dropbox/jrnls/research.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.2
