editor: vim
encrypt: false
tagsymbols: '@'
default_hour: 9
default_minute: 0
timeformat: '%Y-%m-%d %H:%M'
highlight: true
linewrap: 79
template: ~/git/jrnls/template.txt
journals:
  default: ~/git/journal.txt
  work:
    journal: ~/git/jrnls/work.txt
  private:
    journal: ~/git/jrnls/personal.txt
    encrypt: true
  food:
    journal: ~/git/jrnls/food.txt
colors:
  date: MAGENTA
  title: BLUE
version: v2.4.2
