colors:
  date: MAGENTA
  title: BLUE
default_hour: 9
default_minute: 0
editor: vim
encrypt: false
highlight: true
indent_character: '|'
journals:
  default: ~/git/journal.txt
  food:
    journal: ~/git/jrnls/food.txt
  private:
    encrypt: true
    journal: ~/git/jrnls/personal.txt
  work:
    journal: ~/git/jrnls/work.txt
linewrap: 79
tagsymbols: '@'
template: false
timeformat: '%Y-%m-%d %H:%M'
version: v2.4.2
